### ISSUE TITLE
Add support to create a project in KubeSphere workspace

### ISSUE THREAD

**Issue by LinuxSuRen** [LinuxSuRen/ks#71]
Below is an example of a project:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubesphere.io/creator: admin
  finalizers:
  - finalizers.kubesphere.io/namespaces
  labels:
    kubesphere.io/namespace: b2i
    kubesphere.io/workspace: test
  name: b2i
  ownerReferences:
  - apiVersion: tenant.kubesphere.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workspace
    name: test
    uid: 45ed0813-fb91-41d7-af5c-1aa1526d99d4
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

# Why need this?

It can benefit automated tests.
